name: MostlyVanillaRtp
version: ${project.version}
main: com.mostlyvanilla.rtp.MostlyVanillaRtp
api-version: '1.20'
description: Random teleport plugin for Mostly Vanilla

commands:
  rtp:
    description: Randomly teleport to a dimension
    usage: /rtp
  dimensiondisable:
    description: Enable or disable a dimension for RTP
    usage: /dimensiondisable <world>
    permission: mostlyvanilla.rtp.admin
  rtprange:
    description: View or change the RTP min/max radius
    usage: /rtprange [min] [max]
    permission: mostlyvanilla.rtp.admin
