name: MostlyVanillaSpawnStash
version: ${project.version}
main: com.mostlyvanilla.spawnstash.MostlyVanillaSpawnStash
api-version: '1.20'
description: Personal stash room for Mostly Vanilla
softdepend:
  - MostlyVanillaRoles

commands:
  spawnstash:
    description: Spawn a personal stash room around you
    usage: /spawnstash
  delstash:
    description: Delete your stash and restore original blocks
    usage: /delstash
