name: MostlyVanillaShop
version: ${project.version}
main: com.mostlyvanilla.shop.MostlyVanillaShop
api-version: '1.20'
commands:
  shop:
    description: Open the Mostly Vanilla shop
    usage: /shop [reload]
  sell:
    description: Sell item in hand, or /sell all to sell entire inventory
    usage: /sell [all]
  worth:
    description: Browse item sell prices
    usage: /worth
